### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by nikilster** [matthewpalmer/Regift#1]
Thanks so much for creating this!  Was super helpful!

Just to make sure I understand this correctly - # of frames \* frame_delay should equal the length of the video to get a normal speed gif - right?

Also I ported it Objective-C - good times :)

**Comment by matthewpalmer** [comment]
Yeah that's correct. I think iOS does some stuff to optimise at runtime (there is a 'tolerance' value) so the timing might be a little bit off, but shouldn't be too much.
