### ISSUE TITLE
Issues creating GIF

### ISSUE THREAD

**Issue by markmunoz** [matthewpalmer/Regift#13]
Alright so I just got this setup.  I am taking a video and feeding it using:

Regift *test = [[Regift alloc]init];
    NSURL *newGif = [test createGIFFromURL:self.gifURL withFrameCount:16 delayTime:0.2 loopCount:0];

The frame count and delayTime are hardcoded just for testing.

My output logs show a bunch of Called Handler messages and then nothing it just freezes my application there it won't run the next line of code which is an NSLog message for the path it creates.  What am I doing wrong?  Thanks so much for your time and this great library!

**Comment by matthewpalmer** [comment]
Not sure if this is related to your issue, but all of the methods on Regift are class funcs, so you probably shouldn't need to alloc/init anything. (Not a huge fan of having everything being a class func though, so I'd be happy to accept a PR fix if you feel like making it 😀.)

Let me know how that goes!

**Comment by GabiFitcal** [comment]
I have the same issue, can you tell me how do you have solved this problem?

**Comment by matthewpalmer** [comment]
Closing this. Feel free to reopen if the issue persists in master (for non-git submodule installation).

Thanks for your help 👍
