### ISSUE TITLE
Use your library in ObjC

### ISSUE THREAD

**Issue by craffenoux** [matthewpalmer/Regift#2]
Hi, 
Is there a way to use your library in ObjC ?
Thanks

**Comment by matthewpalmer** [comment]
You should be able to, but you'll have to set it up manually. Here is a rough guide
1. Download the Regift.swift file from this repo.
2. Drag it into your Obj-C project.
3. Make sure your build settings are set as per [these instructions](http://stackoverflow.com/questions/24206732/cant-use-swift-classes-inside-objective-c).

Let me know how that goes—I'll reopen if it doesn't work :)

**Comment by lo-fo** [comment]
I had the same problem,
on step 3, i've added :
`
#import "myProjectName-Bridging-Header.h"
#import "myProjectName-Swift.h"
`
and `@objc` on the swift class and on the createGIFFromURL method

**Comment by matthewpalmer** [comment]
@Louis-Fournier what errors/issues specifically are you seeing?

Also just added cocoa pods for this project. Not sure if that helps in this scenario.

**Comment by lo-fo** [comment]
no problems left. i was just adding complementary infos to make it work.
