### ISSUE TITLE
package as cocoapod?

### ISSUE THREAD

**Issue by ryanmeador** [matthewpalmer/Regift#3]
Hi, I'm wondering if you've considered packaging this library as a Cocoapod, now that the latest release of Cocoapods supports Swift?  I'm looking for a library that does what yours does for integration into an Objective C project, and it would be really nice if it was a pod.  Thanks!

**Comment by matthewpalmer** [comment]
Will do. Thanks for the suggestion!

**Comment by matthewpalmer** [comment]
Done. Let me know if there are any issues :)
