### ISSUE TITLE
Getting error with some of videos 

### ISSUE THREAD

**Issue by sanjukhunt** [matthewpalmer/Regift#39]
An error occurred: Optional(Error Domain=AVFoundationErrorDomain Code=-11832 "Cannot Open" UserInfo={NSUnderlyingError=0x17464aaa0 {Error Domain=NSOSStatusErrorDomain Code=-12431 "(null)"}, NSLocalizedFailureReason=This media cannot be used., NSLocalizedDescription=Cannot Open}), image is nil
fatal error: unexpectedly found nil while unwrapping an Optional value

**Comment by eliot1019** [comment]
Hi @sanjukhunt any fix to this issue?

**Comment by sanjukhunt** [comment]
Hello @eliot1019 yes got the issue from the pull requests.
Please refer the following instruction and it will solved crash issues.

https://github.com/matthewpalmer/Regift/pull/37/files

**Comment by menna0ali** [comment]
hello @eliot1019 did you manage to fix this?

**Comment by menna0ali** [comment]
Thank you @sanjukhunt . I tried the solution you suggested. It actually saves the gif now, even though the error still appears. Could you explain why this happens?

**Comment by Linspirit98** [comment]
any update?
