### ISSUE TITLE
AVAssetGenetraor returns nil image

### ISSUE THREAD

**Issue by menna-ali** [matthewpalmer/Regift#40]
Sometimes I encounter an error creating a gif from a video I saved. The error has no specific scenario that I can replicate. I have traced it to find the problem is in this block of code:

[https://github.com/matthewpalmer/Regift/blob/master/Regift/Regift.swift#L299]

**Error text:**

An error occurred: Optional(Error Domain=AVFoundationErrorDomain Code=-11832 "Cannot Open" UserInfo={NSUnderlyingError=0x174440030 {Error Domain=NSOSStatusErrorDomain Code=-12431 "(null)"}, NSLocalizedFailureReason=This media cannot be used., NSLocalizedDescription=Cannot Open}), image is nil

The AVAssetgenerator seems to return nil images sometimes. Anyone has an idea why this happens? I am using swift 3.

Thanks in advance!

**Comment by eliot1019** [comment]
Any fix on this issue?

**Comment by menna0ali** [comment]
found the solution here #39

**Comment by menna-ali** [comment]
found the solution here #39
