### ISSUE TITLE
Gif does not loop

### ISSUE THREAD

**Issue by samuelbeek** [matthewpalmer/Regift#8]
Setting the loop count to 0 or not setting it all results in a non looping animation.

using this code: 
`let gifURL = Regift.createGIFFromURL(URL, withFrameCount: frameCount, delayTime: delayTime)`
[I made this gif](http://fat.gfycat.com/ImpeccableSmoggyGerbil.gif), which does not loop.

**Comment by matthewpalmer** [comment]
Hmm interesting. I’m busy for the next few days, but I’ll take a look at this over the weekend :)

Thanks for letting me know! 👍

**Comment by samuelbeek** [comment]
Cool! thanks a lot. I spend a few hours trying to debug it myself, but did not succeed. Hope you find a solution.

**Comment by samuelbeek** [comment]
Have you had time to look at this?

**Comment by matthewpalmer** [comment]
Yeah had a quick look. Haven't had a chance to implement the fix, but it's related to the way the fileProperties dict is being set up. The dict should be nested, but at the moment it's not. If you want to implement the fix yourself, the gist linked from the end of the README shows how the dictionary should be set up.
I will have a chance to look at it more tomorrow or the next day.

**Comment by samuelbeek** [comment]
Fixed it: https://github.com/matthewpalmer/Regift/pull/9
